# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: CICD variable group
- name: project_name
  value: 'TALEND'
- name: job_name
  value: 'job_feature666'
- name: job_version
  value: '0.1'
- name: docker_image_name
  value: 'CICD'

steps:
  - task: DownloadSecureFile@1
    name: settings_xml
    inputs:
      secureFile: settings.xml

  - task: DownloadSecureFile@1
    name: license
    inputs:
      secureFile: license

  - task: CmdLine@2
    inputs:
      script: 'docker pull openjdk:8-jre-slim'

  - task: Maven@3
    inputs:
        mavenPomFile: '$(project_name)/poms/pom.xml' 
        mavenOptions: |
          -Dlicense.path=$(license.secureFilePath)
          -Dupdatesite.path=$(updatesite_path)
          -Ddocker.push.registry=$(docker_registry)
          -Ddocker.push.username=$(docker_username)
          -Ddocker.push.password=$(docker_password)
          -Xmx3096m -Xmx1024m
        options: '--settings $(settings_xml.secureFilePath) -X -Pdocker -pl jobs/process/$(job_name)_$(job_version) -am -Dtalend.docker.name=$(docker_image_name)'
        goals: 'deploy'
