# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  project_name: TALEND
  nexus_url: http://40.68.59.3:8081

steps:
- task: DownloadSecureFile@1
  name: settings_xml
  inputs:
    secureFile: settings.xml

- task: DownloadSecureFile@1
  name: license
  inputs:
    secureFile: license

- task: Maven@3
  inputs:
      mavenPomFile: '$(project_name)/poms/pom.xml' 
      mavenOptions: '-Dlicense.path=$(license.secureFilePath) -Dupdatesite.path=http://52.178.88.83/toto -Xmx3096m -Xmx1024m' # Optional
      options: '--settings $(settings_xml.secureFilePath) -X'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      publishJUnitResults: false
      goals: 'clean package'
